# Example:
# Players:
#   PlayerUUID: Element
# Trusted:
#   TrustingPlayerUUID: TrustedPlayerUUID
# Energy:
#   PlayerUUID: EnergyAmount
# Lives:
#   PlayerUUID: LivesAmount

Players:

Trusted:

Energy:

Lives:
